Portifolio/Portifolio/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('joshua_admin/', admin.site.urls),
    path('', include('portfolio_app.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Portifolio/portfolio_app/urls.py
from django.urls import path
from .views import *

app_name = 'portfolio_app'

urlpatterns = [
    path('', index, name='index'),
    path('portifolio/', portfolio, name='portfolio'),
    path('project_details/<int:pk>/', portfolio_item_detail, name='detail'),
    path('about/', about, name='about')

]

Portifolio/portfolio_app/models.py
from django.db import models
from django.urls import reverse


class Project(models.Model):
    name = models.CharField(max_length=100)
    overview = models.TextField(max_length=500, blank=True, null=True)
    date_created = models.DateTimeField(auto_now=True)
    date_updated = models.DateTimeField(auto_now_add=True)
    challenges = models.TextField(max_length=500, blank=True, null=True)
    achievements = models.TextField(max_length=500, blank=True, null=True)
    featured_img = models.ImageField(blank=True, null=True)
    alt_text = models.CharField(max_length=100, blank=True, null=True)
    filter_class = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        ordering = ['-date_created']

    def get_absolute_url(self):
        return reverse('portfolio_app:detail', kwargs={'pk': str(self.pk)})

    @property
    def imageURL(self):
        try:
            url = self.featured_img.url

        except:
            url = ''

        print('URL:' + '  ' + url)

        return url

    def __str__(self):
        return self.name


class Image(models.Model):
    project_name = models.ForeignKey(Project, related_name='images', on_delete=models.CASCADE)
    image_name = models.CharField(max_length=30, null=True, blank=True)
    image = models.ImageField()
    alt_text = models.CharField(max_length=100, blank=True, null=True)

    # def __str__(self):
    #     return self.image_name

    @property
    def imageURL(self):
        try:
            url = self.image.url
            print('URL:' + '  ' + url)
        except:
            url = ''
        return url

Portifolio/portfolio_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import *


def index(request):
    project = Project.objects.all()

    context = {
        'portifolio_project': project
    }

    return render(request, 'portifolio_app/index.html', context)


def portfolio(request):
    project = Project.objects.all()

    context = {
        'portifolio_project': project
    }

    return render(request, 'portifolio_app/portifolio.html', context)


def portfolio_item_detail(request, pk):
    project = get_object_or_404(Project, pk=pk)
    images = project.images.all()
    context = {
        'project': project,
        'images': images
    }

    return render(request, 'portifolio_app/detail.html', context)


def about(request):
    return render(request, 'portifolio_app/about.html')

Portifolio/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">

     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="icon" href="https://img.icons8.com/dusk/64/000000/monitor--v1.png">

    <title>
        {% block title %} base {% endblock %}
     </title>
</head>
<body>

<!--navbar-->

<header >
        <div class="navbar">

            <span>
                <button id="open">
                    <i class="fas fa-bars fa-2x menu-icon" ></i>
                </button>
                <span class="menu">Menu</span>
            </span>



                <nav id="mySidenav" class="sidenav">

                    <a href="#"  class="closebtn" id="close">&times;</a>

                    <a href="{% url 'portfolio_app:index'  %}">Home</a>
                    <a href="{% url 'portfolio_app:portfolio' %}">Portifolio</a>
                    <a href="{% url 'portfolio_app:about' %}">About Me</a>
                    <a href="#">Detail</a>
                </nav>

                <ul class="social-links">
                   

                    <li>
                        <a href="#">
                            <i class="fab fa-github fa-2x"></i>
                        </a>
                    </li>


                    <li>
                        <a href="#">
                            <i class="fab fa-twitter fa-2x"></i>
                        </a>
                    </li>

                    <li>
                        <a href="https://api.whatsapp.com/send?phone=256784180208">
                            <i class="fab fa-whatsapp fa-2x"></i>
                        </a>
                    </li>
                </ul>

            </div>



    </header>

<!--navbar end-->


{% block content %}





{% endblock %}

<footer data-aos="fade-up">
        <div class="container">
            <h3>
                Joshua Biyinzika
            </h3>

            <p>
              All rights reserved  &copy; Joshua Biyinzika <span>current date</span>
            </p>
        </div>
</footer>



    <script src="{% static 'js/jqeury.js' %}"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
    <script src="{% static 'js/index.js' %}"></script>

</body>
</html>

Portifolio/templates/portifolio_app/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<title>
        {% block title %} About me {% endblock %}
     </title>

<link rel="stylesheet" href="{% static 'css/about.css' %}">

<!--    <div class="vedio-intro ">-->
<!--        <video class="about-vid" src="./Joshua Portifolio.mp4" controls></video>-->
<!--    </div>-->

    <div class="container about">
        <h2 data-aos="fade-up">
            About Me
        </h2>

        <p data-aos="fade-right">
           Am Joshua,  a freelance junior web developer. <br> I am currentily stationed in Kampala, Uganda. 
        </p>

        <p data-aos="fade-left">
            I work with both Frontend and Backend technologies. <br> 

            I also set up ecommerce stores using shopify.
           
        </p>
    </div>
    
{% endblock %}

Portifolio/templates/portifolio_app/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<title>
        {% block title %} detail {% endblock %}
</title>

<link rel="stylesheet" href="{% static 'css/detail.css' %}">

    <h2 class="project-name" data-aos="fade-down">{{ project.name }}</h2>

    <div class="container">
       

        <div id="featured-project-image" data-aos="zoom-in">
            <img src="{{ project.imageURL }}"  alt="" id="featured-img">
        </div>

        <h3 data-aos="fade-down">
            Navigation
        </h3>

        <div class="slide-wrapper" data-aos="fade-up">
            <button id="arrow-left">
                <i class="fas fa-arrow-left"></i>
            </button>
                

            <div class="slider" id="img-slider">
                {% for img in images %}
                    <img src="{{ img.imageURL }}" class="active thumb" alt="">
                {% endfor %}
            </div>


            <button id="arrow-right">
                <i class="fas fa-arrow-right"></i>
            </button>
        </div>


    </div>

    {% comment %} <section class="video">
        <div class="video-description container">
            <video src="#"></video>
        </div>
    </section> {% endcomment %}

    <section class="description">
        <div class="container">
            <div class="overview" data-aos="fade-right">
                <h2>
                    Project Overview
                </h2>
                <p>
                   {{ project.overview }}
                </p>
            </div>

            <div class="goals" data-aos="fade-left">
                <h2>
                    Project Goals and achievements
                </h2>
                <p>
                   {{ project.achievements }}
                </p>
            </div>

            <div class="achievements" data-aos="fade-right">
                <h2>
                    Project Challenges
                </h2>
                <p>
                    {{ project.challenges }}
                </p>
            </div>
        </div>
    </section>




    <script>
        let thumbnails = document.getElementsByClassName('thumb');
        let featured_img = document.getElementById('featured-img');
        let activeImgs = document.getElementsByClassName('active')
        let arrowLeft = document.getElementById('arrow-left')
        let arrowRight = document.getElementById('arrow-right')

        for (let i=0; i<thumbnails.length; i++){
            thumbnails[i].addEventListener('mouseover', function(){
               
                if (activeImgs.length>0){
                    activeImgs[0].classList.remove('active');
                }

                this.classList.add('active');
                featured_img.src = this.src

            })
        }

        arrowLeft.addEventListener('click', function(){
            
            document.getElementById('img-slider').scrollLeft-=180
        })

        arrowRight.addEventListener('click', function(){
            
            document.getElementById('img-slider').scrollLeft+=180
        })

</script>

{% endblock %}

Portifolio/templates/portifolio_app/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<title>
        {% block title %} Home {% endblock %}
     </title>


    <section class="intro-section" >
        <div class="intro" data-aos="fade-down">
            <div class="intro-head">
                <img src="{% static 'images/joshua_biyinzika.jpg' %}" class="img-fluid" alt="Joshua Biyinzika">
            </div>
            <p class="intro-text">
               Am Joshua, a freelance web developer and blogger.
            </p>

            <div class="intro-btn">
                <a href="#" class="read-more btn btn-lg">Read More</a>
            </div>
           
        </div>
    </section>


    <section class="skills">
        <div class="container skills-container">
            <h2 >
                My skills
            </h2>

            <div class="skill-sets">
                <div class="row">
                    <div class="col-lg-6" data-aos="fade-right">
                        <ul>
                            <li class="item-1">
                                Python
                            </li>
                            <li  class="item-2">
                               Django
                            </li>
                            <li  class="item-3">
                               Flask
                            </li>
                            <li  class="item-4">
                                PostgreSQL
                            </li>
                        </ul>
                    
                    </div>

                    <div class="col-lg-6" data-aos="fade-left">
                        <ul>
                            <li  class="item-4">
                               HTML5
                            </li>
                            <li  class="item-3">
                              CSS3
                            </li>
                            <li  class="item-2">
                              Javascript
                            </li>
                            <li  class="item-1">
                                React js
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="work">
        <div class="container ">
            <div class="samples">
                <h2>
                    Samples of my work
                </h2>
            </div>
            <div class="work-pieces">
                <div class="row">
                    {% for my_project in portifolio_project %}

                    <div class="col-lg-3 col-md-6" data-aos="zoom-in-up">
                         <a href="{{ my_project.get_absolute_url }}">
                        <img src="{{ my_project.featured_img.url }}" alt="" class="img-fluid">
                         </a>
                    </div>

                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="see-more-btn">
            <a href="#" class="see-more btn btn-lg">see more</a>
        </div>
    </section>


    <section class="contact container">
        <h2>
            Let's get in touch
        </h2>
        <div class="form">
            <form  class="form-group"  action="https://formsubmit.co/joshuazoeug@gmail.com" method="post">
                <input data-aos="fade-right" class="form-control initials" type="text" placeholder="Your name" required>
                <input data-aos="fade-left" class="form-control initials" type="email" name="email" placeholder="Your email" required>
                <textarea data-aos="fade-right" class="form-control" name="textarea" placeholder="Your message" cols="30" rows="10" required></textarea>
                <input type="submit" value="Submit" class="btn btn-lg contact-btn">
            </form>
        </div>
    </section>

{% endblock %}
   

    

Portifolio/templates/portifolio_app/portifolio.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<title>
        {% block title %} Portifolio {% endblock %}
     </title>


<link rel="stylesheet" href="{% static 'css/portifolio.css' %}">

    <h1 class="portifolio-heading" data-aos="fade-up">
        My Portfolio
    </h1>
    
<div class="container" data-aos="fade-up">
   <div class="buttons d-flex " id="btn-container">
       <button class="btn btn-lg filter-btn ml-10" id="all" onclick="filterSelectionAll('all')">
           All
       </button>

       <button class="btn btn-lg filter-btn ml-10" id="first" onclick="filterSelectionAll('second')">
        HTML5/CSS3
    </button>

    <button class="btn btn-lg filter-btn ml-10" id="second" onclick="filterSelectionAll('third')">
        DJANGO
    </button>

<!--    <button class="btn btn-lg filter-btn ml-10" id="third" onclick="filterSelectionAll('fourth')">-->
<!--        fourth-->
<!--    </button>-->
   </div>

   <div class="portifolio-items">
       <div class="row">

           {% for item in portifolio_project %}
           <div class="col-lg-3 portifolio-item {{ item.filter_class }}" data-aos="zoom-in-up">
               <a href="{{ item.get_absolute_url }}">
                   <img src="{{ item.featured_img.url }}" alt="" class="img-fluid">
               </a>
           </div>
            {% endfor %}

       </div>
   </div>
</div>





<script>
// filtering portifolio items
filterSelectionAll('all')

    let allBtn = document.getElementById('all');
let firstBtn = document.getElementById('first');
let secondlBtn = document.getElementById('second');
let thirdBtn = document.getElementById('third');
let items = document.getElementsByClassName('portifolio-item')


function filterSelectionAll(range){
    var x, i;
    x = document.getElementsByClassName('portifolio-item');
    if (range == 'all') range = '';

    for (i=0; i<x.length; i++){
        removeClass(x[i], 'show');
        if (x[i].className.indexOf(range) > -1) addClass(x[i], 'show');

    }
}


function addClass(element, name){
    var i, arr1, arr2;
    arr1 = element.className.split(" ");
    arr2 = name.split(" ");

    for (i=0; i<arr2.length; i++){
        if (arr1.indexOf(arr2[i]) == -1){
            element.className += ' ' + arr2[i];
        }
    }
   
}

function removeClass(element, name){
    var i, arr1, arr2;
    arr1 = element.className.split(" ");
    arr2= name.split(" ")
    for (i=0; i<arr2.length; i++){
        while (arr1.indexOf(arr2[i]) > -1){
            arr1.splice(arr1.indexOf(arr2[i]), 1);
        }
    }
    element.className = arr1.join(" ");

}

var btnContainer = document.getElementById('btn-container');

var btn =btnContainer.getElementsByClassName('btn');

for (var i=0; i<btn.length; i++){
    btn[i].addEventListener('click', function(){
        var current = document.getElementsByClassName('active');
        current[0].className = current[0].className.replace('active', '');
        this.className += 'active';
    })
}


</script>


{% endblock %}